# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageConvert.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from ArabicOcr import arabicocr
from kurdish import ku


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(821, 572)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 450, 501, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.openButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openButton.setMinimumSize(QtCore.QSize(0, 50))
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 50))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 791, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.openButton.clicked.connect(self.openImage)
        self.clearButton.clicked.connect(self.clear)
        self.saveButton.clicked.connect(self.saveOutput)




    def clear(self):
        self.textEdit.clear()
        self.textEdit_2.clear()

    def openImage(self):
        

        fname = QtWidgets.QFileDialog.getOpenFileName(None, "Select a file...","", filter=" ")
        joined_string = " ".join(fname)
        imagepath=fname[0]
       
        out_image="output.png"
        results=arabicocr.arabic_ocr(imagepath,out_image)
        myfile= open ('outTxt.txt',"w",encoding='utf-8')
        myfile.write("\n")
        #print(results)
        words=[]

        for i in range(len(results)):
            word=results[i][1]
            words.append(word)

        myfile.write(str(words))
        myfile.close()
        
        file = open("outTxt.txt","r",encoding = "utf-8")

        for satir in file:
            a=file.read()

            text3=ku.Hemwar().transliterate(a)

            self.textEdit.setText(a)
            self.textEdit_2.setText(text3)

    def saveOutput(self):
        fname = QtWidgets.QFileDialog.getSaveFileName(None, "Select a file...","", filter=" ")

        file = open(fname[0],"w",encoding = "utf-8")
        file.write(self.textEdit_2.toPlainText())
        file.close()
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Image Convert"))
        self.clearButton.setText(_translate("Form", "Clear"))
        self.openButton.setText(_translate("Form", "Open Image"))
        self.saveButton.setText(_translate("Form", "Save"))
        self.label.setText(_translate("Form", "İnput"))
        self.label_2.setText(_translate("Form", "Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

