# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textConvert.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Classes import ku

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 575)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 791, 391))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.convertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.convertButton.setMinimumSize(QtCore.QSize(120, 50))
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout.addWidget(self.convertButton)
        self.inputText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.inputText.setObjectName("inputText")
        self.horizontalLayout.addWidget(self.inputText)
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(70, 490, 111, 51))
        self.backButton.setObjectName("backButton")
        self.clearButton = QtWidgets.QPushButton(Form)
        self.clearButton.setGeometry(QtCore.QRect(590, 490, 111, 51))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.convertButton.clicked.connect(self.clickConvert)
        self.clearButton.clicked.connect(self.clickClear)

    def clickConvert(self):

        text1=self.textEdit.toPlainText()
        text2=ku.Hemwar().transliterate(text1)
        self.inputText.setText(text2)
    def clickClear(self):

        self.textEdit.clear()
        


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Text Converter"))
        self.convertButton.setText(_translate("Form", "Convert"))
        self.backButton.setText(_translate("Form", "Back"))
        self.clearButton.setText(_translate("Form", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
